export const popularDestinations = [
  {
    id: "1",
    city: "New York",
    country: "United States",
    code: "JFK",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800",
    price: 299,
  },
  {
    id: "2",
    city: "London",
    country: "United Kingdom",
    code: "LHR",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
    price: 450,
  },
  {
    id: "3",
    city: "Tokyo",
    country: "Japan",
    code: "NRT",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    price: 680,
  },
  {
    id: "4",
    city: "Paris",
    country: "France",
    code: "CDG",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    price: 420,
  },
  {
    id: "5",
    city: "Dubai",
    country: "UAE",
    code: "DXB",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    price: 390,
  },
  {
    id: "6",
    city: "Sydney",
    country: "Australia",
    code: "SYD",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800",
    price: 750,
  },
];
export const testimonials = [
  {
    id: "1",
    name: "Sarah Johnson",
    avatar: "https://i.pravatar.cc/150?img=47",
    rating: 5,
    text: "Booking with Skyward Reserve was seamless. Found a great deal to London in minutes!",
    role: "NYC → London",
  },
  {
    id: "2",
    name: "James Patel",
    avatar: "https://i.pravatar.cc/150?img=12",
    rating: 5,
    text: "The seat selection and check-in process were incredibly smooth. Will definitely use again.",
    role: "Dubai → Tokyo",
  },
  {
    id: "3",
    name: "Emily Chen",
    avatar: "https://i.pravatar.cc/150?img=31",
    rating: 4,
    text: "Great prices and a beautiful interface. Customer support was also very responsive.",
    role: "Sydney → Paris",
  },
];